# Generated by Django 5.1.4 on 2024-12-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_dosaworldmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosaworldmenu',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
